# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('course', 'دوره'), ('service_order', 'سفارش سرویس')], max_length=30, verbose_name='نوع آبجکت')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه آبجکت')),
                ('title_snapshot', models.CharField(blank=True, max_length=255, verbose_name='عنوان (نسخه ذخیره\u200cشده)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'object_type', 'object_id')},
            },
        ),
    ]
