# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد سفارش')),
                ('order_type', models.CharField(choices=[('individual', 'فردی'), ('group', 'گروهی')], max_length=15, verbose_name='نوع سفارش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سفارش')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان کوتاه')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='دانشگاه')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='orders/files/', verbose_name='فایل آپلود شده')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات')),
                ('base_price_toman', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('final_price_per_user_toman', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت نهایی هر نفر (تومان)')),
                ('min_group_members', models.PositiveIntegerField(default=5, verbose_name='حداقل اعضای گروه')),
                ('paid_members_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اعضای پرداخت موفق')),
                ('group_join_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد ورود گروه')),
                ('group_join_link', models.URLField(blank=True, verbose_name='لینک ورود گروه')),
                ('payment_status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('partial', 'پرداخت جزئی (گروهی)')], default='pending_payment', max_length=30, verbose_name='وضعیت پرداخت')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('waiting_group_members', 'در انتظار تکمیل اعضا'), ('waiting_admin_review', 'در انتظار بررسی ادمین'), ('in_production', 'در حال تولید'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('problem', 'دارای مشکل')], default='pending_payment', max_length=30, verbose_name='وضعیت سفارش')),
                ('production_status', models.CharField(choices=[('not_started', 'شروع نشده'), ('waiting_admin_review', 'در انتظار بررسی ادمین'), ('in_progress', 'در حال تولید'), ('done', 'تولید شده')], default='not_started', max_length=30, verbose_name='وضعیت تولید')),
                ('private_channel_link', models.URLField(blank=True, verbose_name='لینک کانال اختصاصی')),
                ('user_note', models.TextField(blank=True, verbose_name='یادداشت کاربر')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='catalog.category', verbose_name='دسته\u200cبندی')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='users.telegramuser', verbose_name='سازنده سفارش')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='catalog.lesson', verbose_name='درس')),
                ('personal_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_orders', to='users.personalpanel', verbose_name='پنل شخصی')),
            ],
            options={
                'verbose_name': 'سفارش سرویس',
                'verbose_name_plural': 'سفارش\u200cهای سرویس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_toman', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پرداختی (تومان)')),
                ('status', models.CharField(choices=[('payment_created', 'ساخته شده'), ('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='payment_created', max_length=30, verbose_name='وضعیت')),
                ('access_status', models.CharField(choices=[('waiting_delivery', 'در انتظار تحویل'), ('delivered', 'تحویل داده شده'), ('problem', 'دارای مشکل')], default='waiting_delivery', max_length=30, verbose_name='وضعیت دسترسی')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='orders.serviceorder', verbose_name='سفارش')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_order_member', to='payments.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_order_memberships', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو سفارش گروهی',
                'verbose_name_plural': 'اعضای سفارش گروهی',
                'ordering': ['-joined_at'],
                'unique_together': {('order', 'user')},
            },
        ),
    ]
