# Generated by Django 5.0.6 on 2026-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان (برای ادمین)')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام بات',
                'verbose_name_plural': 'پیام\u200cهای بات',
                'ordering': ['key'],
            },
        ),
    ]
