# Generated by Django 5.0.6 on 2026-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0003_simplify_course_type_wording'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('text', models.CharField(max_length=255, verbose_name='متن نمایشی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان (برای ادمین)')),
                ('category', models.CharField(choices=[('menu', 'منوی اصلی'), ('button', 'دکمه'), ('status', 'وضعیت'), ('wallet', 'کیف پول'), ('tier', 'نوع نسخه')], default='button', max_length=20, verbose_name='دسته')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب بات',
                'verbose_name_plural': 'برچسب\u200cهای بات',
                'ordering': ['category', 'sort_order', 'key'],
            },
        ),
    ]
