# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('course_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی')], default='free', max_length=10, verbose_name='نوع دوره')),
                ('price_toman', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('full_description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='دانشگاه')),
                ('source_title', models.CharField(blank=True, max_length=255, verbose_name='منبع / مرجع')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات')),
                ('duration_text', models.CharField(blank=True, max_length=100, verbose_name='مدت زمان پادکست')),
                ('episodes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد قسمت\u200cها')),
                ('public_channel_post_link', models.URLField(blank=True, verbose_name='لینک پست کانال عمومی')),
                ('default_private_source_link', models.URLField(blank=True, verbose_name='لینک منبع خصوصی پیش\u200cفرض')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='تصویر کاور')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('coming_soon', 'به\u200cزودی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.category', verbose_name='دسته\u200cبندی')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد خرید')),
                ('payment_status', models.CharField(choices=[('payment_created', 'ساخته شده'), ('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده')], default='payment_created', max_length=30, verbose_name='وضعیت پرداخت')),
                ('access_status', models.CharField(choices=[('waiting_payment', 'در انتظار پرداخت'), ('payment_failed', 'پرداخت ناموفق'), ('payment_verified', 'پرداخت تأیید شده'), ('waiting_personal_panel', 'در انتظار ساخت پنل شخصی'), ('waiting_content_addition', 'در انتظار افزودن محتوا به پنل شخصی'), ('delivered', 'آماده / تحویل داده شده'), ('problem', 'دارای مشکل'), ('cancelled', 'لغو شده')], default='waiting_payment', max_length=30, verbose_name='وضعیت دسترسی')),
                ('access_link', models.URLField(blank=True, verbose_name='لینک دسترسی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='courses.course', verbose_name='دوره')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_purchase', to='payments.payment', verbose_name='پرداخت')),
                ('personal_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_purchases', to='users.personalpanel', verbose_name='پنل شخصی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_purchases', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید دوره',
                'verbose_name_plural': 'خریدهای دوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
