# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد پرداخت')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('amount_rial', models.DecimalField(decimal_places=0, editable=False, max_digits=14, verbose_name='مبلغ (ریال)')),
                ('provider', models.CharField(choices=[('zibal', 'زیبال'), ('wallet', 'کیف پول'), ('manual', 'دستی')], default='zibal', max_length=20, verbose_name='درگاه')),
                ('payment_method', models.CharField(choices=[('zibal_ipg', 'درگاه زیبال'), ('wallet', 'کیف پول')], default='zibal_ipg', max_length=20, verbose_name='روش پرداخت')),
                ('payment_for_type', models.CharField(choices=[('course_purchase', 'خرید دوره'), ('individual_service_order', 'سفارش فردی'), ('group_order_member', 'عضویت سفارش گروهی'), ('wallet_charge', 'شارژ کیف پول')], max_length=30, verbose_name='نوع تراکنش')),
                ('payment_for_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه آبجکت مرتبط')),
                ('status', models.CharField(choices=[('created', 'ساخته شده'), ('request_failed', 'خطا در ساخت درخواست پرداخت'), ('waiting_user_payment', 'در انتظار پرداخت کاربر'), ('callback_received', 'callback دریافت شد'), ('verifying', 'در حال تأیید پرداخت'), ('verified', 'پرداخت موفق و تأیید شده'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده'), ('verification_failed', 'خطا در تأیید پرداخت'), ('already_verified', 'قبلاً تأیید شده'), ('refunded', 'مسترد شده'), ('manual_review', 'نیازمند بررسی دستی')], default='created', max_length=30, verbose_name='وضعیت')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='توضیح')),
                ('order_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه سفارش (ارسالی به زیبال)')),
                ('zibal_track_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='trackId زیبال')),
                ('zibal_result', models.IntegerField(blank=True, null=True, verbose_name='result زیبال')),
                ('zibal_status', models.IntegerField(blank=True, null=True, verbose_name='status زیبال')),
                ('zibal_message', models.CharField(blank=True, max_length=255, verbose_name='پیام زیبال')),
                ('zibal_ref_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع زیبال')),
                ('zibal_card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('zibal_hashed_card_number', models.CharField(blank=True, max_length=255, verbose_name='هش شماره کارت')),
                ('callback_success', models.IntegerField(blank=True, null=True, verbose_name='callback success')),
                ('callback_status', models.IntegerField(blank=True, null=True, verbose_name='callback status')),
                ('callback_payload', models.JSONField(blank=True, null=True, verbose_name='callback payload')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='request payload')),
                ('request_response', models.JSONField(blank=True, null=True, verbose_name='request response')),
                ('verify_payload', models.JSONField(blank=True, null=True, verbose_name='verify payload')),
                ('inquiry_payload', models.JSONField(blank=True, null=True, verbose_name='inquiry payload')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
