# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد کاربر')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='شناسه تلگرام')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل')),
                ('wallet_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کیف پول (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='بلاک شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر تلگرام',
                'verbose_name_plural': 'کاربران تلگرام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد پنل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پنل')),
                ('channel_link', models.URLField(blank=True, null=True, verbose_name='لینک کانال')),
                ('invite_link', models.URLField(blank=True, null=True, verbose_name='لینک دعوت')),
                ('status', models.CharField(choices=[('not_created', 'ساخته نشده'), ('needs_creation', 'نیازمند ساخت توسط ادمین'), ('created', 'ساخته شده'), ('active', 'فعال'), ('problem', 'دارای مشکل')], default='needs_creation', max_length=30, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_panel', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پنل شخصی',
                'verbose_name_plural': 'پنل\u200cهای شخصی',
                'ordering': ['-created_at'],
            },
        ),
    ]
