# Generated by Django 5.0.6 on 2026-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('transaction_type', models.CharField(choices=[('charge', 'شارژ'), ('purchase', 'خرید'), ('refund', 'بازگشت وجه'), ('admin_adjustment', 'تعدیل ادمین')], max_length=20, verbose_name='نوع تراکنش')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payment', verbose_name='پرداخت مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='users.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
    ]
